plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
//    id 'com.android.library'
//    id 'org.jetbrains.kotlin.android'
//    id 'maven-publish'
    id("maven-publish")
}

android {
    namespace = "com.audionowdigital.android.openplayer"
    compileSdk = 36
    ndkVersion = "26.1.10909125"

    defaultConfig {
        minSdk = 21

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")

        externalNativeBuild {
            cmake {
                cppFlags += ""
                arguments += ["-DANDROID_STL=c++_static"]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles(
                    getDefaultProguardFile("proguard-android-optimize.txt"),
                    "proguard-rules.pro"
            )
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/CMakeLists.txt")
        }
    }

    sourceSets {
        main {
            java.srcDirs = ["src"]
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging false
            pickFirsts += ["**/*.so"]
            excludes += ["**/libc++_shared.so"]
        }
        resources {
            excludes += ["**/libc++_shared.so"]
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("com.squareup.okhttp3:okhttp:5.3.2")
}
